P3HPC/p3-analysis-library

.github/workflows/build-unittest.yml, .github/workflows/lint-format.yml
This PR adds Github actions workflows for the following:
- Build and run unit tests for Python 3.8, 3.9, and 3.10
- Run `black` formatter, push changes if any to the working branch, and subsequently run `flake8`
=> Actions for unit tests and code quality

README.md
Prior to this commit, the README was missing two dependencies (specifically numpy and jsonschema). Developers installing the dependencies manually (i.e. without pip) were hitting errors.
N/A
- Add numpy and jsonschema to the dependency list in the README.
- Clarify that a specific version of matplotlib is required.
=> Align README dependencies with pyproject.toml

.github/workflows/commit-signoff-check.yml
This action should check in the latest commit of a pull request or push to make esure it contains "Signed-off-by" in the message, aligning with the DCO requirement in CONTRIBUTING.md
N/A
This PR adds a Github action that will parse commit messages in pull requests and pushes for "Signed-off-by", which is a requirement for DCO sign-off as stated in `CONTRIBUTING.md`.
- Adds a new Github action
- Github action uses `gsactions/commit-message-checker@v2`
- Searches for pattern "Signed-off-by"
The check is rather simplistic but should be reliable. Ideally we would want to capture name and email address to match the contributing guideline exactly, but I don't know a reliable way to capture names using just regex - it's not easy to do it for English (number of words, hyphenation, case), let …
=> Github action for commit sign-off checks

docs/source/data.rst, docs/source/p3-analysis-flowchart.svg
N/A
- Add flowchart showing P3 data collection process.
- Update documentation to outline three stages of P3 analysis and motivation for a database.
---
This was suggested by @tomdeakin over e-mail, so I'd appreciate a quick review from him too.
Note that the steps in the "Coverage" task are slightly different to an earlier version of this diagram that we'd discussed offline.  "Source Code -> Compile & Instrument -> Run -> Extract Coverage" is only one of the possible ways to extract coverage, as something like [Code Base Investigator](https://github.com/intel/code-base-investigator) aims to approximate coverage statically. "Source Code -> Analyze -> Extract Coverage" is generic enough to cover static analysis, run-time analysis of instrumented binaries, sampling, etc.
=> Add flowchart showing P3 data collection process

p3/metrics/_pp.py
Calling agg(harmonic_mean) results in a KeyError when attempting to aggregate over a group with a single member.
N/A
- Wrap `statistics.harmonic_mean` to ensure that it works when passed to `agg`.
=> Replace agg(harmonic_mean) with custom function

.github/workflows/commit-signoff-check.yml
Resolves #15.
Adds a conditional statement in the Github workflow definition for the commit message checker: we will only execute the workflow if "Merge pull request" is __not__ detected in the head commit message.
=> Exclude PR merge commits from sign-off message checking workflow

.github/workflows/lint-format.yml, p3/_utils.py
This PR reconfigures the `black` formatter part of the `lint-format` workflow by removing the autocommit action, and relying on the official `psf` version of the Github action.
The intention now is that the `black` workflow will simply check files within the `p3` source for modifications that `black` _would_ perform, as opposed to making and committing the changes.
Fixes #19 
List out&mdash;with high level descriptions&mdash;what the commits
within this PR do:
- Remove `auto-commit` action which wasn't working as intended, per #19
- Remove Python setup within `black` workflow
- Remove `black` installation within workflow
- Change to using `psf/black@stable` for configuring and running `black` on the code
- Added `black` options per #19; `--check --verbose --diff`
=> Reconfiguring `black` workflow

p3/metrics/_pp.py, p3/plot/_cascade.py, tests/metrics/test_pp.py
N/A
- Enables correct results if dataframe contains multiple results for one (application, platform) pair.
- Selects the best efficiencies for a given (application, platform) pair to ensure correct results.
I considered making `pp` and `cascade` throw an error if the dataframe contained duplicate results, but handling this within the library itself seemed more user-friendly.
=> Drop duplicate results

.github/workflows/build-unittest.yml, .github/workflows/commit-signoff-check.yml, .github/workflows/lint-format.yml
N/A
This PR adds `permissions` entries to the three Github actions workflows to explicitly to `read-all`.
=> Explicit settings for workflow permissions

p3/data/_validation.py, p3/data/coverage-0.1.0.schema
N/A
- Load coverage schema from file to simplify validation code.
- Fix an incorrect URL in the coverage schema itself.
---
The original behavior (with duplication) was implemented primarily because I didn't know how to load a file from the current package.  If reviewers agree that this is a better way to handle our schema files, I'll roll out an equivalent fix to Code Base Investigator shortly.
=> Simplify schema handling

p3/data/_validation.py, p3/data/coverage-0.2.0.schema
The previous schema did not allow for coverage files to contain path information. While a file hash is sufficient to identify uniqueness when computing divergence, a path is more useful to humans and downstream tools.
The new schema allows for coverage files to contain both a file hash and (optional) path information.
N/A
- Update the coverage schema to allow coverage files to contain path information as well as a hash.
- Use the new coverage schema by default.
- Keep the old coverage schema around (for now) because a previous Code Base Investigator release references it.
=> Update coverage schema to 0.2.0

MANIFEST.in
Wasn't sure if it was better to hit you with an issue, or a possible fix (since I'm only 80% on this fix..) but this PR tries to address an issue where your pip install misses a file, causing:
```
File "/Users/robertbird/homebrew/lib/python3.10/site-packages/p3/metrics/_divergence.py", line 75, in _coverage_string_to_json
return _validate_coverage_json(string)
File "/Users/robertbird/homebrew/lib/python3.10/site-packages/p3/data/_validation.py", line 36, in _validate_coverage_json
schema_string = pkgutil.get_data(__name__, "coverage-0.2.0.schema")
File "/Users/robertbird/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 639, in get_data
return loader.get_data(resource_name)
File "<frozen importlib._bootstrap_external>", line …
```
=> Add missing 0.2 schema to fix pip install

.github/workflows/run-precommit.yml
The CI pre-commit action is intended primarily for code review based on how it's written (i.e. using Github SHA refs for diffs) and does not work for `main` branch.
N/A
List out&mdash;with high level descriptions&mdash;what the commits
within this PR do:
- Disable pre-commit workflow trigger for code pushed to `main`
=> Disabling pre-commit run on `main`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md
Closes #29. 
- Remove [Bug] and [Feature request] tags from issue templates.
- Move instructions into comments in pull request template.
=> Update GitHub templates

MANIFEST.in, p3/data/_validation.py, p3/data/coverage-0.3.0.schema, p3/metrics/_divergence.py, tests/data/test_validation.py, tests/metrics/test_divergence.py
Experiments with the old schemas (0.1.0 and 0.2.0) have uncovered two issues:
1) A file hash is not sufficient to identify a file when computing divergence, because a code base may contain duplicates of a file that SHOULD count towards divergence. Accounting for this requires the coverage format to store both the path and a hash.
2) The region format is too closely tied to the operation of specific tools. Each region in the output corresponds to a region of source identified by the producer of the JSON, with no way to recover what the region represents, or which lines within the region are used. As a result, it is impossible touse coverage information from multiple tools (or tool versions).
The new coverage format attempts to address both of these issues by requiring both a file name and …
=> Update coverage schema to 0.3.0

p3/metrics/_divergence.py, p3/report/_snapshot.py
Previously, invoking the divergence function (and any functions that invoke the divergence function, like snapshot) required the P3 and coverage information to be stored in separate tables and connected by a key.
This setup is convenient for data drawn from a database that uses this representation already, but is inconvenient for users reading in data that directly associates a coverage string with each performance result.
This commit makes the cov DataFrame optional: if it exists, then behavior is the same as before; if it does not exist, then the library looks for coverage information stored alongside the P3 data.
N/A
- Make `cov` optional when calling `divergence`.
- Make `cov` optional when calling `snapshot` (which calls `divergence` internally).
- Update documentation for both …
=> Simplify divergence usage by making cov optional

p3/plot/backend/matplotlib.py
The number of applications could exceed the number of markers because:
- We default to matplotlib's list of 16 "filled" markers; or
- A user-provided marker list is too small.
In both cases, an ApplicationStyle can be used to increase the number of markers.
This change effects both Cascade and NavChart plots.
Closes #42.
- Raise an exception if the number of applications is greater than the number of markers.
=> Raise exception if # applications > # markers

p3/plot/backend/matplotlib.py
The platform chart beneath the cascade uses uppercase letters (A-Z) to label each platform. Cascade plots with more than 26 platforms run out of labels.
This is a short term fix to generate a useful error message while we work on a more robust way of assigning platform labels.
Short-term fix for #39. 
- Raise exception for cascades with > 26 platforms.
=> Raise exception for cascades with > 26 platforms

p3/plot/backend/matplotlib.py
A previous change resulted in NavChart storing None instead of a matplotlib Axes object by mistake.
Emphasizes the importance of #37. 
- Assigns NavChart's internal axes object to the named `axes` object returned by `get_axes()`.
=> Fix get_axes() function in NavChart

p3/metrics/_efficiency.py
"date" is named as a column with special meaning in some parts of the documentation. It's therefore potentially surprising if calling application_efficiency can result in the "date" field being stripped.
N/A
- Add "date" to the `filter()` call in `application_efficiency`, so the column is passed through (if it exists).
=> Add "date" to application_efficiency filter

docs/source/analysis.rst, docs/source/conf.py, docs/source/index.rst, docs/source/p3-analysis-flowchart.svg
N/A
- Switch documentation theme and layout to match Code Base Investigator.
- Rewrite the landing page to provide a gentler introduction to the library and P3 analysis.
---
@swright87, I'd appreciate it if you (and/or one of your students) could also take a look at this new text.
=> Update documentation theme

.github/workflows/test-gallery.yml
This workflow tests that examples and case studies in the gallery execute correctly, and saves any plots produced as artifacts for visual inspection.
It does not test that the documentation builds correctly with Sphinx.
Closes #37. 
- Run every Python file in examples/ and upload any *.png files as part of an examples ZIP.
- Run every Python file in case-studies/ and upload any *.png files as part of a case-studies ZIP.
There's nothing in this PR that makes any attempt to check that the PNGs are correct, because I think the only way to do that is going to be via visual inspection. But the validation will fail if no PNGs are produced.
It may be possible to improve on this further by uploading a separate artifact for each output graph, but I couldn't figure out how to do this with my …
=> Add a new workflow to test the gallery

p3/metrics/_pp.py, p3/plot/_cascade.py, p3/plot/backend/matplotlib.py, p3/plot/backend/pgfplots.py, tests/metrics/test_pp.py
Removing data from a user-supplied DataFrame might impact certain properties of the data (e.g., the order in which applications, platforms, and/or problems appear).
Rather than complicate our implementation with workarounds that might not address every possible use-case, we can simply detect and reject problematic data.
This effectively reverts #22.  It's an alternative solution to the one proposed in #63. 
- Reject duplicate (application, platform) pairs when calculating PP and plotting cascades.
- Prevent `pp` from sorting implicitly during its `groupby` operation.
- Update tests to match new expected behavior.
---
The upshot of the changes here is intended to be:
- For simple datasets with no duplicate results, there is no change in behavior.
- For complex datasets with duplicate …
=> Reject duplicate results when handling efficiencies

examples/metrics/application_efficiency.py, examples/metrics/multiple_components.py, examples/metrics/projection.py
This new example demonstrates how to use per-component (per-kernel) timings to calculate per-component application efficiencies, and how to accurately calculate overall application efficiency when per-component timings are available.
Blocked by #55, which is why this is in draft state.  I'd like to add cross-references between examples once they're merged.
- Add a more complex example of using application efficiency, inspired by the SYCL CRK-HACC paper.
---
@swright87, @laserkelvin: One thing I am really unhappy about here is how complicated it is to extract the sum/min from the result of a pandas grouping and append it to the original data.  I'm sure there must be a better way to do it than this, but functions like `unstack`, `melt` and `pivot` didn't seem to do what I wanted.  If you …
=> Add draft of per-component example

p3analysis/plot/backend/matplotlib.py, p3analysis/plot/backend/pgfplots.py, tests/plot/test_navchart.py
Due to a copy-paste error, NavChart was looking for columns with the "eff" suffix instead of columns with the "pp" suffix.
N/A
- Check for the correct columns in both matplotlib and pgfplots backends.
- Add a simple regression test to make sure we don't accidentally break this again.
=> Fix navchart column

p3analysis/plot/_cascade.py, p3analysis/plot/_navchart.py
Before introducing classes like `ApplicationStyle`, passing all styling options via `kwargs` made sense. Now that there are effectively separate `kwargs` lists for different aspects of the plot, those options should be exposed as part of the interface.
Closes #46.
- Moves styling options out of `kwargs`.
- Adds an `*` to `cascade` and `navchart` to separate positional arguments from keyword arguments.
- Adds documentation for "backend" option that was previously missing.
---
While working on this I realized an advantage of the `matplotlib`-style list of `kwargs` that I hadn't noticed before.  With `kwargs`, it is very easy to define shorthands because everything is just a key in a dictionary (e.g., `linestyle` and `ls` refer to the same option).
We should be cognizant of the fact that …
=> Move plot styling options out of kwargs

p3analysis/_utils.py, p3analysis/metrics/_efficiency.py, p3analysis/metrics/_pp.py, p3analysis/plot/_cascade.py, p3analysis/plot/_navchart.py, p3analysis/plot/backend/matplotlib.py, p3analysis/plot/backend/pgfplots.py, tests/metrics/test_efficiency.py, tests/metrics/test_pp.py, tests/plot/test_cascade.py, tests/plot/test_navchart.py
Closes #43.
- Add extra unit tests related to validation of numeric types.
- Cast columns that we expect to be numeric to numeric before running any operations.
=> Fix validation of numeric types

p3analysis/plot/backend/__init__.py, p3analysis/plot/backend/matplotlib.py, p3analysis/plot/backend/pgfplots.py
Closes #39.
- Switch to AA, AB, AC, AD labels for very large plots, increasing the upper limit to 676 platforms.
- Tweak default plotting parameters for large plots to make them readable.
---
Clearly 676 platforms is too many, and I don't think anybody will ever want to produce such a large plot.  But this change allows us to handle plots with many platforms without crashing.  There will still be cases where the plot is unreadable, but the user can work around that by increasing the plot size.
Here's an example of 30 platforms, where the default is now readable:
By the time we hit 50 platforms, things are pretty squished:
I'm pretty happy with this as a fix for now, because most studies I've seen in real life use somewhere between 1-10 platforms.  Fixing this for the general case will …
=> Improve handling of large cascade plots

docs/source/index.rst
N/A
- Add a warning to the main page that the documentation should be considered unstable.
---
@swright87 had previously complained that the documentation didn't reflect that latest functionality.  The idea of the change in this PR is to make it clear that the online documentation is unstable, allowing us to push the latest changes to the live website ahead of the P3 Tooling panel at P3HPC.
=> Mark online documentation unstable
